-- =============================================================================
-- Tennis Longueuil: core schema
--
-- Tables:   player_levels, profiles, lessons, lesson_registrations
-- Triggers: updated_at maintenance, profile creation for new auth users,
--           lessons.registered_count maintenance
--
-- Security (RLS, grants) lives in 20260921000200_security.sql.
-- RPC functions live in 20260921000300_rpc_functions.sql.
-- =============================================================================

-- Internal helpers live in a schema that is NOT exposed through the Data API.
create schema if not exists private;
revoke all on schema private from public;

-- -----------------------------------------------------------------------------
-- Enumerated types
-- -----------------------------------------------------------------------------

create type public.user_role as enum ('player', 'admin');

create type public.lesson_status as enum ('scheduled', 'cancelled', 'completed');

-- A waitlist can be added later with:
--   alter type public.registration_status add value 'waitlisted';
-- Capacity logic only ever counts 'joined' rows, so a new status does not
-- change existing behaviour.
create type public.registration_status as enum ('joined', 'cancelled');

-- -----------------------------------------------------------------------------
-- Shared trigger function: keep updated_at current
-- -----------------------------------------------------------------------------

create function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- player_levels: admin-managed skill levels (informational in V1)
-- -----------------------------------------------------------------------------

create table public.player_levels (
  id smallint generated by default as identity primary key,
  name text not null,
  -- Ordering key. Seeded with gaps of 10 so new levels can be inserted between.
  rank smallint not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint player_levels_name_key unique (name),
  constraint player_levels_rank_key unique (rank),
  constraint player_levels_name_length check (length(btrim(name)) between 1 and 40)
);

comment on table public.player_levels is
  'Tennis skill levels. Only admins assign levels to players (see admin_set_member_level).';

insert into public.player_levels (name, rank) values
  ('Beginner', 10),
  ('Intermediate', 20),
  ('Advanced', 30),
  ('Competitive', 40);

-- -----------------------------------------------------------------------------
-- profiles: one row per auth user
-- -----------------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null,
  phone text,
  -- Storage object path inside the "avatars" bucket. The only allowed value is
  -- '<user id>/profile.jpg', so a profile can never point at someone else's
  -- file or an external URL. The client derives the public URL from it.
  avatar_path text,
  role public.user_role not null default 'player',
  player_level_id smallint references public.player_levels (id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_full_name_length check (length(btrim(full_name)) between 1 and 80),
  constraint profiles_phone_format check (phone is null or phone ~ '^[0-9+() .-]{7,30}$'),
  constraint profiles_avatar_path_owner check (avatar_path is null or avatar_path = id::text || '/profile.jpg')
);

comment on table public.profiles is
  'Member profile. role, player_level_id and active can only be changed by admins through RPC functions.';

create index profiles_player_level_id_idx on public.profiles (player_level_id);

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function private.set_updated_at();

-- Create a profile whenever the coach creates an auth user.
-- The role is ALWAYS 'player' (column default). It is never read from
-- raw_user_meta_data, because users can edit their own metadata.
create function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    left(
      coalesce(
        nullif(btrim(new.raw_user_meta_data ->> 'full_name'), ''),
        nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
        'New player'
      ),
      80
    )
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

-- -----------------------------------------------------------------------------
-- lessons
-- -----------------------------------------------------------------------------

create table public.lessons (
  id uuid primary key default gen_random_uuid(),
  title text not null default 'Tennis Lesson',
  description text,
  start_time timestamptz not null,
  end_time timestamptz not null,
  location text not null default 'Complexe Sportif Longueuil',
  court_count integer not null default 1,
  -- Business rule: maximum 4 players per court. Derived, never client-supplied.
  capacity integer not null generated always as (court_count * 4) stored,
  -- Number of 'joined' registrations. Maintained by trigger, never client-supplied.
  registered_count integer not null default 0,
  -- Optional target level (informational). NULL means "All levels".
  player_level_id smallint references public.player_levels (id) on delete set null,
  registration_open boolean not null default true,
  registration_deadline timestamptz,
  status public.lesson_status not null default 'scheduled',
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lessons_title_length check (length(btrim(title)) between 1 and 80),
  constraint lessons_location_length check (length(btrim(location)) between 1 and 120),
  constraint lessons_description_length check (description is null or length(description) <= 1000),
  constraint lessons_time_order check (end_time > start_time),
  constraint lessons_max_duration check (end_time - start_time <= interval '12 hours'),
  constraint lessons_court_count_range check (court_count between 1 and 20),
  constraint lessons_deadline_before_start check (
    registration_deadline is null or registration_deadline <= start_time
  ),
  -- Last line of defence against overbooking, whatever path writes the data.
  -- Also stops an admin from reducing courts below the current registrations.
  constraint lessons_registered_count_range check (
    registered_count >= 0 and registered_count <= court_count * 4
  )
);

comment on table public.lessons is
  'Tennis lessons. Only admins create/edit/cancel. Lessons are cancelled (status), never deleted.';

create index lessons_start_time_idx on public.lessons (start_time);
create index lessons_created_by_idx on public.lessons (created_by);
create index lessons_player_level_id_idx on public.lessons (player_level_id);

create trigger lessons_set_updated_at
  before update on public.lessons
  for each row execute function private.set_updated_at();

-- -----------------------------------------------------------------------------
-- lesson_registrations
-- -----------------------------------------------------------------------------

create table public.lesson_registrations (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references public.lessons (id) on delete cascade,
  player_id uuid not null references public.profiles (id) on delete cascade,
  status public.registration_status not null default 'joined',
  joined_at timestamptz not null default now(),
  cancelled_at timestamptz,
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- One row per player per lesson. Re-joining reactivates the same row.
  constraint lesson_registrations_lesson_player_key unique (lesson_id, player_id),
  constraint lesson_registrations_reason_length check (
    cancellation_reason is null or length(cancellation_reason) <= 500
  ),
  -- Only cancelled registrations carry cancellation data. Together with the RLS
  -- policy (other players only see 'joined' rows) this guarantees a private
  -- cancellation reason is never readable by other players.
  constraint lesson_registrations_cancellation_consistency check (
    (status = 'cancelled' and cancelled_at is not null)
    or (status <> 'cancelled' and cancelled_at is null and cancellation_reason is null)
  )
);

comment on table public.lesson_registrations is
  'Registrations are never deleted: cancelling sets status = cancelled. Writes only through join_lesson / cancel_registration.';

create index lesson_registrations_lesson_status_idx on public.lesson_registrations (lesson_id, status);
create index lesson_registrations_player_id_idx on public.lesson_registrations (player_id);

create trigger lesson_registrations_set_updated_at
  before update on public.lesson_registrations
  for each row execute function private.set_updated_at();

-- Keep lessons.registered_count equal to the number of 'joined' rows.
--
-- The lesson row is locked BEFORE counting. Under READ COMMITTED the count then
-- runs with a fresh snapshot that includes every committed registration, so
-- the lessons_registered_count_range check is a true backstop: even a writer
-- that bypassed join_lesson could not overbook a lesson under concurrency.
--
-- FOR NO KEY UPDATE (not FOR UPDATE) because inserting a registration takes a
-- FOR KEY SHARE lock on the lesson through its foreign key; FOR UPDATE would
-- conflict with that and deadlock concurrent writers. The same lock mode is
-- used by join_lesson, cancel_registration and admin_set_member_active.
--
-- Updating the lesson row also emits a Realtime event that every member may
-- receive, without exposing any registration details.
create function private.refresh_registered_count(p_lesson_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform 1 from public.lessons l where l.id = p_lesson_id for no key update;

  update public.lessons l
     set registered_count = (
       select count(*) from public.lesson_registrations r
        where r.lesson_id = p_lesson_id and r.status = 'joined'
     )
   where l.id = p_lesson_id;
end;
$$;

create function private.sync_lesson_registered_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op <> 'INSERT' then
    perform private.refresh_registered_count(old.lesson_id);
  end if;

  if tg_op = 'INSERT' or (tg_op = 'UPDATE' and new.lesson_id is distinct from old.lesson_id) then
    perform private.refresh_registered_count(new.lesson_id);
  end if;

  return null;
end;
$$;

create trigger lesson_registrations_sync_count
  after insert or delete or update of status, lesson_id on public.lesson_registrations
  for each row execute function private.sync_lesson_registered_count();
